wording
fiskaltrust/faq pull request #131
Opened 2021-02-18 15:46 UTC by fabry-training

2021-02-18 15:53 UTC, fabry-training commented
Angebot

2021-02-19 09:43 UTC, magdignomad requested changes

2021-02-19 09:43 UTC, magdignomad commented on qna/DE-shop-clearing-entitlement.md
> +Im fiskaltrust.Portal finden Sie unter <kbd>Shop</kbd>  &rarr;  <kbd>Produkte</kbd> das Angebot der fiskaltrust. Das sind neben dem Basis-Produkt, der fiskaltrust.Middleware, kostenpflichtige Addon-P
Die kostenfreie fiskaltrust.Middleware ist nicht direkt im Shop verfügbar (oder?)
Sollten wir fiskaltrust.Docs nicht direkt an die richtige Position verlinken (bessere UX)?

2021-02-22 13:04 UTC, aedler-ft approved these changes

2021-02-22 13:06 UTC, aedler-ft approved these changes

2021-02-22 13:07 UTC, aedler-ft approved these changes

2021-02-22 13:08 UTC, merged